"""Generate or register AI-created visual assets with manifest provenance.

This helper has three useful modes:

1. `--provider placeholder` creates a simple planning PNG and logs the prompt.
2. `--provider openai` calls OpenAI's image generation API when OPENAI_API_KEY exists.
3. `--import-file path/to/image.png` registers an image generated by another tool.

Examples:
    python tools/video-use/helpers/generate_asset.py --prompt "clean icon of a camera lens" --project-dir edit/demo
    python tools/video-use/helpers/generate_asset.py --provider openai --prompt "cinematic moon base" --model gpt-image-1
    python tools/video-use/helpers/generate_asset.py --import-file assets/generated/frame.png --prompt "..."
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import textwrap
from pathlib import Path
from typing import Any

import requests

from asset_manifest import add_asset_entry, load_env, utc_now


OPENAI_IMAGES_URL = "https://api.openai.com/v1/images/generations"


def parse_size(size: str) -> tuple[int, int]:
    if "x" not in size:
        raise argparse.ArgumentTypeError("size must look like 1024x1024")
    width, height = size.lower().split("x", 1)
    return int(width), int(height)


def safe_name(value: str, fallback: str = "generated-asset") -> str:
    keep = []
    for char in value.lower().strip():
        if char.isalnum():
            keep.append(char)
        elif char in {" ", "-", "_"}:
            keep.append("-")
    name = "".join(keep).strip("-")
    while "--" in name:
        name = name.replace("--", "-")
    return (name[:80] or fallback)


def create_placeholder(prompt: str, output: Path, size: tuple[int, int]) -> Path:
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError as exc:
        raise RuntimeError(
            "Pillow is required for placeholder generation. Install project "
            "dependencies or use --import-file to register an existing asset."
        ) from exc

    output.parent.mkdir(parents=True, exist_ok=True)
    width, height = size
    image = Image.new("RGB", size, "#1f2933")
    draw = ImageDraw.Draw(image)

    try:
        font_title = ImageFont.truetype("DejaVuSans-Bold.ttf", max(24, width // 28))
        font_body = ImageFont.truetype("DejaVuSans.ttf", max(16, width // 48))
    except Exception:
        font_title = ImageFont.load_default()
        font_body = ImageFont.load_default()

    draw.rectangle((0, 0, width, height), fill="#1f2933")
    draw.rectangle((24, 24, width - 24, height - 24), outline="#8aa4b8", width=4)
    draw.text((48, 48), "GENERATED ASSET PLACEHOLDER", fill="#e5eef5", font=font_title)

    wrapped = textwrap.wrap(prompt, width=max(28, width // 18))
    y = 120
    for line in wrapped[:12]:
        draw.text((48, y), line, fill="#cbd8e3", font=font_body)
        y += max(22, height // 32)

    draw.text((48, height - 72), utc_now(), fill="#8aa4b8", font=font_body)
    image.save(output)
    return output


def generate_openai(prompt: str, output: Path, model: str, size: str, extra: dict[str, Any]) -> Path:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is missing; use --provider placeholder or --import-file instead.")

    payload: dict[str, Any] = {
        "model": model,
        "prompt": prompt,
        "size": size,
        "n": 1,
    }
    payload.update(extra)

    response = requests.post(
        OPENAI_IMAGES_URL,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json=payload,
        timeout=120,
    )
    response.raise_for_status()
    data = response.json()
    image_data = (data.get("data") or [{}])[0]

    output.parent.mkdir(parents=True, exist_ok=True)
    if image_data.get("b64_json"):
        output.write_bytes(base64.b64decode(image_data["b64_json"]))
        return output
    if image_data.get("url"):
        image_response = requests.get(image_data["url"], timeout=120)
        image_response.raise_for_status()
        output.write_bytes(image_response.content)
        return output
    raise RuntimeError("OpenAI image response did not include b64_json or url.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate or register image assets with manifest provenance.")
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--negative-prompt", default="")
    parser.add_argument("--provider", default="placeholder", choices=["placeholder", "openai"])
    parser.add_argument("--model", default=None)
    parser.add_argument("--model-version", default=None)
    parser.add_argument("--seed", default=None)
    parser.add_argument("--size", default="1024x1024", help="Width x height, e.g. 1024x1024.")
    parser.add_argument("--project-dir", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, help="Output image path. Defaults under project/assets/generated.")
    parser.add_argument("--title", default=None)
    parser.add_argument("--import-file", type=Path, help="Register an existing generated asset instead of generating.")
    parser.add_argument("--extra-json", default="{}", help="Extra provider JSON merged into API request/manifest metadata.")
    args = parser.parse_args()

    load_env()
    extra = json.loads(args.extra_json)
    size_tuple = parse_size(args.size)

    title = args.title or args.prompt
    output = args.output
    if output is None:
        output = args.project_dir / "assets" / "generated" / f"{safe_name(title)}.png"

    provider = args.provider
    model = args.model
    if args.import_file:
        local_path = args.import_file.resolve()
        provider = "imported" if provider == "placeholder" else provider
    elif provider == "placeholder":
        local_path = create_placeholder(args.prompt, output.resolve(), size_tuple)
        model = model or "placeholder"
    elif provider == "openai":
        model = model or os.environ.get("OPENAI_IMAGE_MODEL", "gpt-image-1")
        local_path = generate_openai(args.prompt, output.resolve(), model, args.size, extra)
    else:
        raise SystemExit(f"unsupported provider: {provider}")

    entry = {
        "source_platform": provider,
        "asset_type": "generated_image",
        "asset_id": local_path.stem,
        "asset_title": title,
        "creator": "AI-generated",
        "local_path": str(local_path),
        "downloaded_at": utc_now(),
        "generation_provider": provider,
        "model": model,
        "model_version": args.model_version,
        "prompt": args.prompt,
        "negative_prompt": args.negative_prompt,
        "seed": args.seed,
        "input_references": extra.get("input_references"),
        "generation_date": utc_now(),
        "policy_or_license_notes": "Generated asset; verify provider terms and do not present as factual evidence.",
        "metadata": {"size": args.size, "extra": extra},
    }
    manifest_path, asset = add_asset_entry(args.project_dir, entry)
    print(json.dumps({"manifest": str(manifest_path), "asset": asset}, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
